### ISSUE TITLE
Create conditional runtime environment for gcp-config docker image

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/gcp-config#7]
Currently, we've added runtime conditions to the stctl command for use during execution from Cloud Build. Instead, we want a runtime environment that interprets conditional directives like `--execute_in_project=<foo>` before calling `exec` on the remaining parameters passed to the docker image.

I imagine a new command `cbenv` or `cbexec` or `cbopt` or `cbcond` or similar, that accepts parameters from the environment and then execs the rest of argv if the conditions for execution are satisfied.

The first condition it should support is "EXECUTE_IN_PROJECTS=". With this directive it will be possible to have a single cloud build config with commands that should only be run in specific projects.

```
- name: gcp-config
  args: [ 'echo', 'hello world' ]
  env:
  - EXECUTE_IN_PROJECTS=mlab-sandbox,mlab-staging,mlab-oti
```

Additional ideas include conditional action on built-in environment variables -- https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values  For example, `IF_TAG_SET`, or `IF_TAG_MATCHES=<pattern>`.
